**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
#Code here
# vector of size 10 with all zeros
vec = np.zeros(10)

print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [4]:
#Code here
# Take input
a = int(input("Enter number of rows (a): "))
b = int(input("Enter number of columns (b): "))

# Generate random array of shape (a, b)
arr = np.random.randint(1, 100, size=(a, b))  # numbers between 1 and 99

# Print array
print("Generated Array:")
print(arr)

# Calculate average
avg = np.mean(arr)

print("Average of array:", avg)

Enter number of rows (a): 1
Enter number of columns (b): 10
Generated Array:
[[74 66 11 56 60  3 49 14 37 99]]
Average of array: 46.9


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [7]:
#Code here

def border_array(a, b):
    # create array filled with 1s
    arr = np.ones((a, b), dtype=int)

    # set inner elements to 0 (exclude border)
    if a > 2 and b > 2:
        arr[1:-1, 1:-1] = 0

    return arr


# example
result = border_array(4, 4)
print(result)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [9]:
#Code here
vec=np.random.random((1,10))
vec

array([[0.08842848, 0.40240202, 0.18706466, 0.58816097, 0.93301407,
        0.84597179, 0.35611299, 0.83996848, 0.7235922 , 0.38668712]])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [10]:
#Code here
# A true identity matrix is always square (n × n), so a 3×4 identity matrix doesn’t exist in the strict sense
import numpy as np

mat = np.eye(3, 4)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [12]:
#Code here
arr = np.arange(5).reshape(1, 5)
arr = arr.repeat(5, axis=0)
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [13]:
#code here
import numpy as np

# given point
point = np.array([2, 3])

# random coordinates (10 points, each with x,y)
coords = np.random.randint(1, 101, size=(10, 2))

print("Coordinates:\n", coords)

# compute Euclidean distance
dist = np.sqrt(np.sum((coords - point) ** 2, axis=1))

# convert to integer type
dist = dist.astype(int)

print("Distances:\n", dist)

Coordinates:
 [[36 83]
 [16 51]
 [38 76]
 [33 31]
 [57 73]
 [65 44]
 [ 2 91]
 [21 25]
 [28 92]
 [56 84]]
Distances:
 [86 50 81 41 89 75 88 29 92 97]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [14]:
#Code here
import numpy as np

np.unravel_index(99, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [15]:
#Code here
import numpy as np

# take input
arr = input().split()

# convert to float NumPy array
arr = np.array(arr, dtype=float)

# reverse the array
arr = arr[::-1]

# print result
print(arr)

2
[2.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
import numpy as np

arr = np.array([])

print("elements_count :", arr.size)

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [16]:
#Code here
import numpy as np

def softmax(arr):
    # check if input is numpy array
    if not isinstance(arr, np.ndarray):
        raise TypeError("Input must be a NumPy array")

    # check if 1D
    if arr.ndim != 1:
        raise ValueError("Input must be a 1D NumPy array")

    # numerical stability trick (avoid overflow)
    shifted = arr - np.max(arr)

    exp_vals = np.exp(shifted)
    softmax_vals = exp_vals / np.sum(exp_vals)

    return softmax_vals


# example
x = np.array([1.0, 2.0, 3.0])
print(softmax(x))

[0.09003057 0.24472847 0.66524096]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [17]:
#Coder here
import numpy as np

def vstack_arrays(*arrays):
    # check if at least one array is passed
    if len(arrays) == 0:
        raise ValueError("At least one array is required")

    # validate all inputs
    for arr in arrays:
        if not isinstance(arr, np.ndarray):
            raise TypeError("All inputs must be NumPy arrays")

    # perform vertical stack
    result = np.vstack(arrays)

    return result


# example
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print(vstack_arrays(a, b))

[[1 2]
 [3 4]
 [5 6]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [18]:
#Code here
import numpy as np
from datetime import datetime, timedelta

def date_array(start_date, end_date):
    # type check
    if not isinstance(start_date, str) or not isinstance(end_date, str):
        raise TypeError("Both inputs must be strings")

    # parse dates (format: YYYY-M-D)
    try:
        start = datetime.strptime(start_date, "%Y-%m-%d")
        end = datetime.strptime(end_date, "%Y-%m-%d")
    except:
        raise ValueError("Date format must be YYYY-M-D (e.g., 2022-12-6)")

    # same year check
    if start.year != end.year:
        raise ValueError("Dates must be from the same year")

    # start <= end check
    if start > end:
        raise ValueError("Start date must be <= end date")

    # generate dates
    days = (end - start).days
    dates = [start + timedelta(days=i) for i in range(days + 1)]

    # convert to numpy array of strings
    result = np.array([d.strftime("%Y-%m-%d") for d in dates])

    return result


# example
print(date_array("2022-12-6", "2022-12-10"))

['2022-12-06' '2022-12-07' '2022-12-08' '2022-12-09' '2022-12-10']


###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [19]:
#Code hereimport numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# compute mean of each row (keep dimensions for broadcasting)
row_mean = np.mean(arr, axis=1, keepdims=True)

# subtract row mean from each row
result = arr - row_mean

print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-16:` Replace odd elements in arrays with -1.

In [20]:
#Code here
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# replace odd numbers with -1
arr[arr % 2 != 0] = -1

print(arr)

[-1  2 -1  4 -1  6]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [21]:
#Code here
import numpy as np

a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

result = np.maximum(a, b)
print(result)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [22]:
#Code here
import numpy as np

arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8,5)

# alternate columns
alt_cols = arr1[:, ::2]

# normalization
xmin = arr1.min()
xmax = arr1.max()
norm_arr = (arr1 - xmin) / (xmax - xmin)

print("Original:\n", arr1)
print("\nAlternate Columns:\n", alt_cols)
print("\nNormalized:\n", norm_arr)

Original:
 [[2315 4282 2903 7654 6006]
 [6151 1069 4480 8745 8438]
 [9625 8502 4939 6932 8607]
 [2817 2128  837 5443 6527]
 [3027  486 5734 7286 8625]
 [6378 7682 2120   22 1271]
 [1294 4057 3815 3028 6272]
 [2375 6955 1205 3755 7301]]

Alternate Columns:
 [[2315 2903 6006]
 [6151 4480 8438]
 [9625 4939 8607]
 [2817  837 6527]
 [3027 5734 8625]
 [6378 2120 1271]
 [1294 3815 6272]
 [2375 1205 7301]]

Normalized:
 [[0.23877955 0.44361137 0.30001041 0.79475164 0.6231386 ]
 [0.63823805 0.10902843 0.46422993 0.90836197 0.87639279]
 [1.         0.88305738 0.51202749 0.7195668  0.89399146]
 [0.29105488 0.21930647 0.08486931 0.56451109 0.67739248]
 [0.31292304 0.04831823 0.59481412 0.75643028 0.89586588]
 [0.6618765  0.7976674  0.21847339 0.         0.13006352]
 [0.13245861 0.42018119 0.39498074 0.31302718 0.65083828]
 [0.2450276  0.72196189 0.12319067 0.38873269 0.75799229]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [23]:
#Code here
import numpy as np

def nth_largest(arr, n):
    # check type
    if not isinstance(arr, np.ndarray):
        raise TypeError("arr must be a NumPy array")

    # check 1D
    if arr.ndim != 1:
        raise ValueError("arr must be 1D")

    # check n
    if not isinstance(n, int) or n <= 0 or n > len(arr):
        raise ValueError("n must be an integer and n <= len(arr)")

    # use partition (efficient, no full sort)
    result = np.partition(arr, -n)[-n]

    return result


# examples
arr = np.array([12,34,40,7,1,0])
print(nth_largest(arr, 3))  # 12
print(nth_largest(arr, 1))  # 40

12
40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [24]:
#code here
import numpy as np

a = np.array([1, 2, 3])

part1 = np.repeat(a, len(a))   # [1 1 1 2 2 2 3 3 3]
part2 = np.tile(a, len(a))     # [1 2 3 1 2 3 1 2 3]

result = np.concatenate((part1, part2))
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
