###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [1]:
# code here
# APPROACH:
# 1. Create random 3x4 matrix.
# 2. Perform different types of sorting:
#    i. Normal row-wise sort
#    ii. Sort by 2nd column
#    iii. Sort by maximum value in each row
#    iv. Sort all elements globally

# TC: O(n log n)
# SC: O(n)

import numpy as np

# Random matrix
arr = np.random.randint(0, 101, (3, 4))

print("Original Matrix:\n", arr)

# ---------------------------------------------------
# i. Sort matrix row-wise
# ---------------------------------------------------
sorted_matrix = np.sort(arr)

print("\nRow-wise Sorted Matrix:\n", sorted_matrix)

# ---------------------------------------------------
# ii. Sort based on 2nd column
# ---------------------------------------------------
second_col_sort = arr[arr[:, 1].argsort()]

print("\nSorted by 2nd Column:\n", second_col_sort)

# ---------------------------------------------------
# iii. Sort based on maximum value in each row
# ---------------------------------------------------
max_row_sort = arr[arr.max(axis=1).argsort()]

print("\nSorted by Max Value in Each Row:\n", max_row_sort)

# ---------------------------------------------------
# iv. Sort all elements globally
# ---------------------------------------------------
all_sorted = np.sort(arr, axis=None)

print("\nAll Elements Sorted:\n", all_sorted)

Original Matrix:
 [[33 33 38 66]
 [46 18 85 95]
 [52 57 37  6]]

Row-wise Sorted Matrix:
 [[33 33 38 66]
 [18 46 85 95]
 [ 6 37 52 57]]

Sorted by 2nd Column:
 [[46 18 85 95]
 [33 33 38 66]
 [52 57 37  6]]

Sorted by Max Value in Each Row:
 [[52 57 37  6]
 [33 33 38 66]
 [46 18 85 95]]

All Elements Sorted:
 [ 6 18 33 33 37 38 46 52 57 66 85 95]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [2]:
# code here
# APPROACH:
# 1. Convert lists into NumPy arrays.
# 2. Add extra subject as new column.
# 3. Add two new student records as rows.
# 4. Compute total marks column.
# 5. Sort based on total marks in descending order.
# 6. Show top 2 students.

# TC: O(n log n)
# SC: O(n)

import numpy as np

# Given marks array
marks = np.array([
    [13, 10,  9, 33],
    [63, 46, 90, 42],
    [39, 76, 13, 29],
    [82,  9, 29, 78],
    [67, 61, 59, 36]
])

# Extra subject marks
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1, 1)

# ---------------------------------------------------
# i. Add extra subject column
# ---------------------------------------------------
marks = np.hstack((marks, extra_subject))

print("After Adding Extra Subject:\n")
print(marks)

# ---------------------------------------------------
# ii. Add two new student records
# ---------------------------------------------------
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

marks = np.vstack((marks, rec1, rec2))

print("\nAfter Adding Two Students:\n")
print(marks)

# ---------------------------------------------------
# iii. Add total marks column
# ---------------------------------------------------
total = marks.sum(axis=1).reshape(-1, 1)

marks = np.hstack((marks, total))

print("\nAfter Adding Total Marks Column:\n")
print(marks)

# ---------------------------------------------------
# iv. Sort by total marks descending
# ---------------------------------------------------
sorted_marks = marks[marks[:, -1].argsort()[::-1]]

print("\nTop 2 Students:\n")
print(sorted_marks[:2])

After Adding Extra Subject:

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

After Adding Two Students:

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]

After Adding Total Marks Column:

[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]

Top 2 Students:

[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [3]:
# code here
# APPROACH:
# Use np.unique() with axis parameter.
# axis=0 -> unique rows
# axis=1 -> unique columns

# TC: O(n log n)
# SC: O(n)

import numpy as np

arr = np.array([
    [1, 2, 3, 3, 1, 1],
    [0, 9, 1, 2, 8, 8],
    [1, 2, 3, 8, 8, 8],
    [1, 2, 3, 3, 1, 1]
])

# ---------------------------------------------------
# Unique rows
# ---------------------------------------------------
row_unique = np.unique(arr, axis=0)

print("Row Wise Unique:\n")
print(row_unique)

# ---------------------------------------------------
# Unique columns
# ---------------------------------------------------
col_unique = np.unique(arr, axis=1)

print("\nColumn Wise Unique:\n")
print(col_unique)

Row Wise Unique:

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Column Wise Unique:

[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [4]:
# code here
# APPROACH:
# Flip rows and columns simultaneously.
# Use np.flip() or slicing.

# TC: O(n)
# SC: O(1)

import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Flip along both axes
result = np.flip(arr)

print(result)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [5]:
# code here
# APPROACH:
# Check rows where any element is greater than X.
# Use boolean masking with np.any().
# Then get row indexes using np.where().

# TC: O(n*m)
# SC: O(n)

import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 8, 6],
    [7, 1, 2],
    [0, 5, 1]
])

X = 6

# Find rows having any element > X
rows = np.where(np.any(arr > X, axis=1))[0]

print(rows)

[1 2]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [6]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [7]:
# code here
# APPROACH:
# Combine multiple arrays into one flat array
# using np.concatenate().

# TC: O(n)
# SC: O(n)

import numpy as np

# Given arrays
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)

# Convert into flat 1D array
result = np.concatenate((arr1, arr2, arr3))

print(result)

[0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [8]:
# code here
# APPROACH:
# 1. Find minimum and maximum values.
# 2. Remove them using boolean masking.

# TC: O(n)
# SC: O(n)

import numpy as np

np.random.seed(400)

arr = np.random.randint(100, 1000, 200).reshape((1, 200))

# Find minimum and maximum
min_val = arr.min()
max_val = arr.max()

print("Minimum Value:", min_val)
print("Maximum Value:", max_val)

# Remove min and max elements
result = arr[(arr != min_val) & (arr != max_val)]

print("\nArray after removing min and max:\n")
print(result)

Minimum Value: 103
Maximum Value: 998

Array after removing min and max:

[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
 353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
 921 490 527 972 278 307 840 958 246 449 251 957 627 920 824 356 825 173
 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211 771
 270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922 967
 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325 729
 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395 525
 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618 226
 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291 194
 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883 588]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [9]:
# code here
# APPROACH:
# 1. Limit values between 100 and 200 using np.clip().
# 2. Sort the array.
# 3. Compute cumulative sum using np.cumsum().

# TC: O(n log n)
# SC: O(n)

import numpy as np

# Random array
arr = np.array([50, 120, 350, 180, 700, 90, 210, 150])

print("Original Array:\n", arr)

# ---------------------------------------------------
# Limit values between 100 and 200
# ---------------------------------------------------
clipped = np.clip(arr, 100, 200)

print("\nAfter Limiting Values:\n", clipped)

# ---------------------------------------------------
# Sort the array
# ---------------------------------------------------
sorted_arr = np.sort(clipped)

print("\nSorted Array:\n", sorted_arr)

# ---------------------------------------------------
# Cumulative Sum
# ---------------------------------------------------
cumsum_arr = np.cumsum(sorted_arr)

print("\nCumulative Sum:\n", cumsum_arr)

Original Array:
 [ 50 120 350 180 700  90 210 150]

After Limiting Values:
 [100 120 200 180 200 100 200 150]

Sorted Array:
 [100 100 120 150 180 200 200 200]

Cumulative Sum:
 [ 100  200  320  470  650  850 1050 1250]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [10]:
# code here
# APPROACH:
# 1. Generate array values between 0 and 1.
# 2. Round values to 3 decimal places.
# 3. Compare:
#    0th percentile  -> minimum value
#    100th percentile -> maximum value
# 4. Find difference between 51st and 50th percentile.

# TC: O(n log n)
# SC: O(n)

import numpy as np

# Random array in range [0,1]
np.random.seed(0)

arr = np.random.random(20)

# ---------------------------------------------------
# Round to 3 decimal places
# ---------------------------------------------------
arr = np.round(arr, 3)

print("Rounded Array:\n", arr)

# ---------------------------------------------------
# Percentiles
# ---------------------------------------------------
p0 = np.percentile(arr, 0)
p100 = np.percentile(arr, 100)

print("\n0th Percentile :", p0)
print("Minimum Value  :", arr.min())

print("\n100th Percentile :", p100)
print("Maximum Value    :", arr.max())

# ---------------------------------------------------
# Difference between 51st and 50th percentile
# ---------------------------------------------------
p50 = np.percentile(arr, 50)
p51 = np.percentile(arr, 51)

diff = p51 - p50

print("\n50th Percentile :", p50)
print("51st Percentile :", p51)

print("\nDifference :", diff)

Rounded Array:
 [0.549 0.715 0.603 0.545 0.424 0.646 0.438 0.892 0.964 0.383 0.792 0.529
 0.568 0.926 0.071 0.087 0.02  0.833 0.778 0.87 ]

0th Percentile : 0.02
Minimum Value  : 0.02

100th Percentile : 0.964
Maximum Value    : 0.964

50th Percentile : 0.5854999999999999
51st Percentile : 0.59215

Difference : 0.006650000000000045
